### ISSUE TITLE
Error while trying to use TinyMCE widget

### ISSUE THREAD

**Issue by amartya-dev** [jazzband/django-tinymce#279]
Traceback:

Traceback (most recent call last):
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    return render_value_in_context(output, context)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/template/base.py", line 971, in render_value_in_context
    value = str(value)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/utils/html.py", line 373, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/forms/widgets.py", line 63, in __str__
    return self.render()
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/forms/widgets.py", line 78, in render
    return mark_safe('\n'.join(chain.from_iterable(getattr(self, 'render_' + name)() for name in MEDIA_TYPES)))
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/forms/widgets.py", line 97, in <genexpr>
    ] for medium in media)
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/forms/widgets.py", line 96, in <listcomp>
    ) for path in self._css[medium]
  File "/home/amartya/envs/itsprimemedia/lib/python3.6/site-packages/django/forms/widgets.py", line 105, in absolute_path
    if path.startswith(('http://', 'https://', '/')):
AttributeError: 'ellipsis' object has no attribute 'startswith'
[23/Jul/2020 17:39:48] "GET /people/upload_article/ HTTP/1.1" 500 185925

Process finished with exit code 0

If there is something I am doing wrong I would appreciate any help

**Comment by jammon** [comment]
I think it would help if you looked at or posted the template you are trying to render here. Looks like django gets an ellipsis (`...`) where a path / string is expected.

**Comment by claudep** [comment]
You probably have some leftover `...` in the the Media.css definition in one of your forms (maybe a copy-paste from the docs). I don't see anything related to django-tinymce.
