### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'tinymce/tinymce.min.js'

### ISSUE THREAD

**Issue by FaberYeah** [jazzband/django-tinymce#430]
Hello,

I've updated django-tinymce from 3.5.0 to 3.6.0, deploying it to Heroku I get this error: `ValueError: Missing staticfiles manifest entry for 'tinymce/tinymce.min.js'`

Full build log:

```$ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_372fc8f3/manage.py", line 22, in <module>
           main()
         File "/tmp/build_372fc8f3/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
           django.setup()
         File "/app/.heroku/python/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
           app_config.import_models()
         File "/app/.heroku/python/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
           self.models_module = import_module(models_module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
         File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 940, in exec_module
         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
         File "/app/.heroku/python/lib/python3.11/site-packages/tinymce/models.py", line 7, in <module>
           from tinymce import widgets as tinymce_widgets
         File "/app/.heroku/python/lib/python3.11/site-packages/tinymce/widgets.py", line 23, in <module>
           import tinymce.settings
         File "/app/.heroku/python/lib/python3.11/site-packages/tinymce/settings.py", line 35, in <module>
           staticfiles_storage.url("tinymce/tinymce.min.js"),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 173, in url
           return self._url(self.stored_name, name, force)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 152, in _url
           hashed_name = hashed_name_func(*args)
                         ^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 472, in stored_name
           raise ValueError(
       ValueError: Missing staticfiles manifest entry for 'tinymce/tinymce.min.js'
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.```
      
Is this a known bug?

F.

**Comment by claudep** [comment]
Do you have `tinymce` in your INSTALLED_APPS?

**Comment by andrei-shabanski** [comment]
The error occurs when STATICFILES_STORAGE is `ManifestStaticFilesStorage`. With StaticFilesStorage everything works fine.

**Comment by claudep** [comment]
I have an instance where collectstatic is running fine with django-tinymce 3.6.0 AND `ManifestStaticFilesStorage`. So we'll need more information to debug this.

**Comment by andrei-shabanski** [comment]
Any manage.py command fails with the following traceback:

```
Traceback (most recent call last):
  File "<project-dir>/manage.py", line 15, in <module>
    management.execute_from_command_line()
  File "<venv-dir>/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "<venv-dir>/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "<venv-dir>/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<venv-dir>/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "<venv-dir>/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<venv-dir>/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<venv-dir>/lib/python3.11/site-packages/tinymce/models.py", line 7, in <module>
    from tinymce import widgets as tinymce_widgets
  File "<venv-dir>/lib/python3.11/site-packages/tinymce/widgets.py", line 23, in <module>
    import tinymce.settings
  File "<venv-dir>/lib/python3.11/site-packages/tinymce/settings.py", line 35, in <module>
    staticfiles_storage.url("tinymce/tinymce.min.js"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<venv-dir>/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 173, in url
    return self._url(self.stored_name, name, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<venv-dir>/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 152, in _url
    hashed_name = hashed_name_func(*args)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<venv-dir>/lib/python3.11/site-packages/django/contrib/staticfiles/storage.py", line 472, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'tinymce/tinymce.min.js'
```

Seems that the error occurs during initializing django apps due to tinymce/settings.py:35 line `staticfiles_storage.url("tinymce/tinymce.min.js")`

python 3.11
django 4.1.7

Some lines from settings.py:

```
tinymce in INSTALLED_APPS
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = ROOT_PATH / 'assets'
STATIC_URL = 'https://cdn.example.com/'
STATICFILES_DIRS = (
    ROOT_PATH / 'static',
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
```

**Comment by andrei-shabanski** [comment]
@claudep Try to cleanup `STATIC_ROOT` directory and run any manage.py commands with `DEBUG = False`. 

In that case, `staticfiles_storage.url("tinymce/tinymce.min.js")` (tinymce/settings.py:35) should raise the error during initializing django apps cause the staticfiles manifest is empty

**Comment by claudep** [comment]
@jameyg: I guess we'll have to revert db466745ad008, as calling `staticfiles_storage.url` directly in `tinymce.settings` is probably too soon in the starting process. I guess we should find a way to delay that access with some lazy utility.

**Comment by claudep** [comment]
Thanks for reporting. django-tinymce 3.6.1 was just released.

**Comment by FaberYeah** [comment]
Thank you @claudep , I confirm that with 3.6.1 version the deploy was smooth.

Keep up the good work! 🙏
