### ISSUE TITLE
ModuleNotFoundError Django

### ISSUE THREAD

**Issue by Emad-Eldin-G** [jazzband/django-tinymce#443]
When installing the django-tinymce package, everything works fine.  

Howevere when running python manage.py migrate, I get the following error (log included):
`Traceback (most recent call last):
  File "/Users/omda/Desktop/FULL-STACK/manage.py", line 22, in <module>
    main()
  File "/Users/omda/Desktop/FULL-STACK/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/omda/Desktop/Computerizervenv/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/omda/Desktop/Computerizervenv/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/Users/omda/Desktop/Computerizervenv/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/omda/Desktop/Computerizervenv/venv/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/omda/Desktop/Computerizervenv/venv/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tinymceParts'`

Not sure what the cause is as I did everything exactly as the documentation stated

**Comment by Emad-Eldin-G** [comment]
Tinymce version = Latest
Django version = 4.0.8

**Comment by merwok** [comment]
That looks like a missing comma between `'tinymce'` and `'parts'`

**Comment by Emad-Eldin-G** [comment]
Hmmmm, I do have an app in my project called Parts actually. 
How can I solve it ?

**Comment by Emad-Eldin-G** [comment]
I just realized I forgot the comma after tinymce in the installed apps :!

**Comment by Emad-Eldin-G** [comment]
It migrates now, but text areas are still the same on the admin panel
